// THIS IS AN AUTO-GENERATED CLASS. DO NOT MODIFY.    
// generated by GenCounter on Wed Jul 30 12:05:37 PDT 2008
package scalanlp.counters.ints;

import scala.collection.mutable.Map;
import scala.collection.mutable.HashMap;

trait Int2ShortCounter extends ShortCounter[Int] {


  abstract override def update(k : Int, v : Short) = {

    super.update(k,v);
  }

  // this isn't necessary, except that the jcl MapWrapper overrides put to call Java's put directly.
  override def put(k : Int, v : Short) :Option[Short] = { val old = get(k); update(k,v); old}

  abstract override def -=(key : Int) = {

    super.-=(key);
  }
  override def default(k : Int) : Short = 0;

  override def apply(k : Int) : Short = super.apply(k);



  // TODO: clone doesn't seem to work. I think this is a JCL bug.
  override def clone(): Int2ShortCounter  = super.clone().asInstanceOf[Int2ShortCounter]

  override  def argmax() : Int = (elements reduceLeft ((p1:(Int,Short),p2:(Int,Short)) => if (p1._2 > p2._2) p1 else p2))._1
  override  def argmin() : Int = (elements reduceLeft ((p1:(Int,Short),p2:(Int,Short)) => if (p1._2 < p2._2) p1 else p2))._1

  override  def max : Short = values reduceLeft ((p1:Short,p2:Short) => if (p1 > p2) p1 else p2)
  override  def min : Short = values reduceLeft ((p1:Short,p2:Short) => if (p1 < p2) p1 else p2)

  override  def comparator(a : Int, b :Int) = apply(a) compare apply(b);

  override  def normalized : Int2DoubleCounter = {
    val normalized = new HashMap[Int,Double]() with Int2DoubleCounter;
    val total : Double = this.total
    for (pair <- elements) {
      normalized.put(pair._1,pair._2 / total)
    }
    normalized
  }

  override  def l2norm() : Double = {
    var norm = 0.0
    for (val v <- values) {
      norm += (v * v)
    }
    return Math.sqrt(norm)
  }

  override  def topK(k : Int) = Counters.topK[(Int,Short)](k,(x,y) => (x._2-y._2).asInstanceOf[Int])(this);

  def dot(that : Int2ShortCounter) : Double = {
    var total = 0.0
    for (val (k,v) <- that.elements) {
      total += get(k).asInstanceOf[Double] * v
    }
    return total
  }

  def +=(that : Int2ShortCounter) {
    for(val (k,v) <- that.elements) {
      update(k,(this(k) + v).asInstanceOf[Short]);
    }
  }

  override  def +=(that : Iterable[(Int,Short)]) {
    for(val (k,v) <- that) {
      this(k) = (this(k) + v).asInstanceOf[Short];
    }
  }


}


object Int2ShortCounter {
  import it.unimi.dsi.fastutil.objects._
  import it.unimi.dsi.fastutil.ints._
  import it.unimi.dsi.fastutil.shorts._
  import it.unimi.dsi.fastutil.longs._
  import it.unimi.dsi.fastutil.floats._
  import it.unimi.dsi.fastutil.doubles._


  import scala.collection.jcl.MapWrapper;
  def apply() = new MapWrapper[Int,Short] with Int2ShortCounter {
    private val under = new Int2ShortOpenHashMap;
    def underlying() = under.asInstanceOf[java.util.Map[Int,Short]];
    override def apply(x : Int) = under.get(x);
    override def update(x : Int, v : Short) {
      val oldV = this(x);
      updateTotal(v-oldV);
      under.put(x,v);
    }
  }

  
}

